import {buildings,technologies,sectors,fresh,costOf,canPay,build,research,conquer,mine,advance,restore,multiplier,prestige,prestigeReward} from './engine.mjs';
const $=id=>document.getElementById(id),names={ore:'광석',energy:'에너지',alloy:'합금',science:'과학',fleet:'함대'},icons={ore:'◇',energy:'ϟ',alloy:'▧',science:'⌬',fleet:'△'},key='exo-industries-v1';
const fmt=n=>new Intl.NumberFormat('ko-KR',{maximumFractionDigits:n<10?1:0,notation:n>=1e6?'compact':'standard'}).format(n);
let raw=null;try{raw=localStorage.getItem(key)}catch{}let state=restore(raw),tab='overview',paused=false,lastSave=Date.now(),toastTimer;
const elapsed=advance(state);function toast(text){$('toast').textContent=text;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3500)}
function save(){try{localStorage.setItem(key,JSON.stringify(state));$('save-status').textContent='자동 저장 활성'}catch{$('save-status').textContent='저장 실패 · 저장 공간 확인'}}
function costHTML(cost){return Object.entries(cost).map(([r,n])=>`<span class="${state.resources[r]<n?'missing':''}">${names[r]} ${fmt(n)}</span>`).join(' · ')}
function buildingHTML(b){const locked=b.tech&&!state.tech.includes(b.tech),cost=costOf(b,state);return `<article class="card ${locked?'locked':''}"><div class="card-top"><span class="card-icon">${b.id==='mine'?'◇':b.id==='solar'?'ϟ':b.id==='factory'?'▧':b.id==='lab'?'⌬':'△'}</span><span class="card-count">보유 ${state.buildings[b.id]} 시설</span></div><h3>${b.name}</h3><p>${b.desc}</p><div class="cost">${costHTML(cost)}</div><button class="buy" data-build="${b.id}" ${locked||!canPay(state,cost)?'disabled':''}>${locked?'선행 연구 필요':'+ 시설 건설'}</button></article>`}
function render(){
 $('resources').innerHTML=Object.entries(names).map(([r,n])=>`<div class="resource"><div class="resource-label">${n}<span>${icons[r]}</span></div><b>${fmt(state.resources[r])}</b><small>${r==='ore'?'채굴 · 건설 자원':r==='energy'?'생산망의 동력':r==='alloy'?'공업 · 우주 건설':r==='science'?'기술 발전 자원':'영토 확장 전력'}</small></div>`).join('');
 const headings={overview:['작전 개요','지구의 마지막 산업 혁명은 당신의 손에서 시작됩니다.'],build:['생산 시설','생산망을 연결하세요. 원료나 에너지가 부족하면 해당 시설이 멈춥니다.'],research:['기술 연구','산업 자동화에서 특이점까지, 새로운 시대를 열어보세요.'],conquest:['영토 확장','지구를 통합하고 새로운 행성의 자원을 확보하세요.']};
 $('heading').textContent=headings[tab][0];$('subtitle').textContent=headings[tab][1];$('phase').textContent=state.conquests>=6?'PHASE 04 / 성간 제국':state.tech.includes('space')?'PHASE 03 / 우주 시대':state.tech.includes('industry')?'PHASE 02 / 산업 시대':'PHASE 01 / 채굴 시대';
 $('summary').textContent=`생산 배율 ×${fmt(multiplier(state))} · 환생 ${state.meta.rebirths}회 · 영구 포인트 ${fmt(state.meta.points)} · 누적 정복 ${state.meta.conquests}개`;
 const content=$('content');
 if(tab==='overview')content.innerHTML=`<div class="overview-grid"><section class="panel"><div class="panel-heading"><h2>지구 자원 채굴</h2><span>TERRA / SOL SYSTEM</span></div><div class="planet-stage"><div class="orbit"></div><div class="orbit second"></div><div class="planet"></div><span class="planet-label">SECTOR 001 · HOMEWORLD</span></div><button class="mine-button" data-mine ${state.reserve<=0?'disabled':''}>${state.reserve<=0?'지구 자원 고갈':'광석 채굴 +'+(state.tech.includes('industry')?3:1)+' ◇'}</button><div class="reserve-label"><span>지구 잔여 매장량</span><span>${fmt(state.reserve)} / 20,000</span></div><progress max="20000" value="${state.reserve}"></progress><p class="warning">지구 자원은 유한합니다. 달 전초기지를 확보하면 지구 고갈 이후에도 채굴할 수 있습니다. 막히면 환생해 새 지구에서 다시 시작하세요.</p></section><section class="panel"><div class="panel-heading"><h2>다음 작전</h2><span class="goal-number">${String(state.conquests+1).padStart(2,'0')} / 07</span></div><h3 class="mission-title">${sectors[state.conquests]?.name??'은하 산업 제국 완성'}</h3><p class="mission-description">${sectors[state.conquests]?.desc??'이 우주의 정복을 완료했습니다. 환생으로 더 강력한 제국을 건설하세요.'}</p><div class="checklist">${[['산업 자동화',state.tech.includes('industry')],['행성 물류망',state.tech.includes('logistics')],['성간 항법',state.tech.includes('space')],['외계 자원 확보',state.conquests>=2]].map(([n,ok])=>`<div class="check ${ok?'complete':''}"><span>${ok?'✓':'○'}</span>${n}</div>`).join('')}</div><button class="buy" data-go="conquest">영토 확장 확인 →</button><div class="callout">환생 예상 보상: 영구 포인트 +${prestigeReward(state)}<br>포인트 1당 생산량 +10%. 누적 기록과 영구 포인트는 다음 우주에 이어집니다.</div><button class="buy" style="margin-top:12px" data-prestige>환생 · 새로운 우주 시작</button></section></div><div class="section-heading"><h2>기초 생산망</h2><span>BUILD YOUR FOUNDATION</span></div><div class="cards">${buildings.slice(0,2).map(buildingHTML).join('')}</div>`;
 if(tab==='build')content.innerHTML=`<div class="callout">시설 설명의 생산량은 기본값입니다. 현재 전체 생산 배율은 ×${fmt(multiplier(state))}. 자동 생산은 채굴 → 발전 → 합금 → 연구 → 함대 순서로 처리됩니다.</div><div class="section-heading"><h2>산업 인프라</h2><span>5 FACILITY TYPES</span></div><div class="cards">${buildings.map(buildingHTML).join('')}</div>`;
 if(tab==='research')content.innerHTML=`<div class="cards">${technologies.map(t=>{const done=state.tech.includes(t.id),locked=t.requires&&!state.tech.includes(t.requires);return `<article class="card ${locked?'locked':''}"><div class="card-top"><span class="card-icon">⌬</span><span class="card-count">${done?'연구 완료':'TECHNOLOGY'}</span></div><h3>${t.name}</h3><p>${t.desc.replace('解금','해금')}</p><div class="cost">${costHTML(t.cost)}</div><button class="buy" data-research="${t.id}" ${done||locked||!canPay(state,t.cost)?'disabled':''}>${done?'✓ 연구 완료':locked?'선행 연구 필요':'기술 연구'}</button></article>`}).join('')}</div>`;
 if(tab==='conquest')content.innerHTML=sectors.map((s,i)=>{const done=i<state.conquests,locked=i>state.conquests||!state.tech.includes(s.requires);return `<article class="panel territory ${locked?'locked':''}"><span class="territory-index">${String(i+1).padStart(2,'0')}</span><div class="body"><h3>${s.name}</h3><p>${s.desc}</p><div class="cost">${costHTML(s.cost)}</div></div><button class="buy" data-conquer ${done||locked||!canPay(state,s.cost)?'disabled':''}>${done?'✓ 통합 완료':i>state.conquests?'이전 영토 필요':locked?'선행 연구 필요':'영토 통합 →'}</button></article>`}).join('');
}
function switchTab(next){tab=next;document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));render()}
function sync(){if(!paused)advance(state);else state.timestamp=Date.now()}
function refresh(){const active=document.activeElement;const focus=active?.dataset?Object.entries(active.dataset)[0]:null;render();if(focus){const replacement=document.querySelector(`[data-${focus[0]}="${focus[1]}"]`);replacement?.focus({preventScroll:true})}}
 document.addEventListener('click',e=>{const button=e.target.closest('button');if(!button||button.disabled)return;sync();if(button.dataset.tab)switchTab(button.dataset.tab);if(button.dataset.go)switchTab(button.dataset.go);if('mine'in button.dataset)mine(state);if(button.dataset.build&&build(state,button.dataset.build))toast('생산 시설을 건설했습니다.');if(button.dataset.research&&research(state,button.dataset.research))toast('새 기술을 확보했습니다.');if('conquer'in button.dataset&&conquer(state))toast('새 영토가 제국에 통합되었습니다.');if('prestige'in button.dataset&&confirm(`이 우주의 진행을 초기화하고 영구 포인트 ${prestigeReward(state)}개를 얻을까요? 누적 기록은 유지됩니다.`)){state=prestige(state);toast('새 우주에서 제국을 다시 시작합니다.')}refresh();save()});
 $('pause').addEventListener('click',()=>{sync();paused=!paused;$('pause').textContent=paused?'생산 재개':'일시정지';save()});
 $('reset').addEventListener('click',()=>{if(confirm('영구 포인트와 누적 기록을 포함해 모든 데이터를 삭제할까요?')){state=fresh();paused=false;$('pause').textContent='일시정지';save();render()}});
 setInterval(()=>{sync();refresh();if(Date.now()-lastSave>=3000){save();lastSave=Date.now()}},1000);
 window.addEventListener('pagehide',()=>{sync();save()});document.addEventListener('visibilitychange',()=>{sync();save();refresh()});render();save();if(elapsed>60)toast(`지난 ${Math.floor(elapsed/60)}분의 자동 생산을 반영했습니다. (최대 8시간)`);
